### PR TITLE
Make Step 0 visible again

### PR DESCRIPTION
**Pull request by sinsukehlab**
### Summary

Step 0 is invisible now.

### Changes

- Revert 0f79722
- Remove the **Start course** button
- Update the discussions link in X-finish.md
- Cherry-pick skills/copilot-codespaces-vscode@3f7b03b (skills/copilot-codespaces-vscode#58)
- Cherry-pick skills/copilot-codespaces-vscode@892fbd5 (skills/copilot-codespaces-vscode#126)
- Cherry-pick skills/copilot-codespaces-vscode@eb258a9 (skills/copilot-codespaces-vscode#132)
- Cherry-pick skills/copilot-codespaces-vscode@b4773f8 (skills/copilot-codespaces-vscode#137)

### Task list

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by sinsukehlab** [comment]
@arelia @mockra @ericdrosado @smashwilson Please review this PR.

**Comment by morganersery1** [comment]
After a review, we will not be moving forward with the suggested changes in the pull request. This is the conclusion due to the fact that Step 0 does not contain any relevant information and does not need to be visible in order for the successful completion of the Primer.

**Comment by sinsukehlab** [comment]
@morganersery1 I believe that Step 0 contains some relevant information. This course was prepared with Step 0 as the starting point. I have also cherry-picked some commits from Skills template for improvement. I would like to ask you to reconsider this PR. Suggestions are welcome.

**Comment by morganersery1** [comment]
@sinsukehlab As a part of the transfer from the Skills template to this course, we moved all information from Step 0 to Step 1. Our Engineers thoroughly reviewed and we've concluded that there is nothing there that you would be missing within Step 0. You're welcome to share additional feedback and suggestions as new PR's. When you do so, please share your recommended reason for the update.

**Comment by sinsukehlab** [comment]
@morganersery1 You have not moved any information from Step 0 to Step 1.
There have been no commits drastically changing README.md except one made by the bot since this repository was generated using the Skills template (the initial commit of this repository).
Cf. https://github.com/education/primer-copilot/commits/main/README.md
The commit 0f79722, which I am trying to revert, updated the Step from 0 to 1.
The commit ea3861d only changed the discussion link in the footer of README.md.
Now the main of README.md is the same as the Step 1 file 1-copilot-extension.md, which has not been changed since the initial commit.
Also, I have executed the diff command below in my local environment and verified that the Step 1 files of this repository and the Skills template have the same content.
```shell
diff copilot-codespaces-vscode/.github/steps/1-copilot-extension.md primer-copilot/.github/steps/1-copilot-extension.md
```

**Pull request closed without merging**
